CMAKE_BINARY_DIR=$PWD && \
CMAKELISTS_NAME=CMakeLists.txt && \
CMAKELISTS_DIR=$CMAKE_BINARY_DIR/$CMAKELISTS_NAME && \
BUILD_DIR=$CMAKE_BINARY_DIR/build && \

cmake -B $BUILD_DIR -DCMAKE_BUILD_TYPE=Release -G Ninja && \
cmake --build $BUILD_DIR